// Copyright (c) 2026 Brad Root
// SPDX-License-Identifier: MPL-2.0

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import fs from 'fs';
import os from 'os';
import path from 'path';
import {
  formatOidentdConfig,
  registerIdent,
  unregisterIdent,
  isOidentdFileEnabled,
  oidentdFilePath,
  initOidentdFile,
  stopOidentdFile,
  whenOidentdSettled,
  type IdentEntry,
} from './identd.js';

const entry = (over: Partial<IdentEntry> = {}): IdentEntry => ({
  localAddress: '198.51.100.5',
  localPort: 40000,
  remoteAddress: '203.0.113.7',
  remotePort: 6697,
  ident: 'alice',
  ...over,
});

// Let the coalesced writer flush AND its async write settle.
const flush = (): Promise<void> => whenOidentdSettled();

describe('formatOidentdConfig', () => {
  it('emits only the header when there are no entries', () => {
    const out = formatOidentdConfig([]);
    expect(out).toBe(
      '# Generated by Lurker — do not edit; overwritten on every IRC (dis)connect.\n',
    );
  });

  it('renders the full 4-tuple to/fport/from/lport form per entry', () => {
    const out = formatOidentdConfig([entry()]);
    expect(out).toContain(
      'to 203.0.113.7 fport 6697 from 198.51.100.5 lport 40000 { reply "alice" }\n',
    );
  });

  it('renders one line per live connection', () => {
    const out = formatOidentdConfig([
      entry({ ident: 'alice', localPort: 40000 }),
      entry({ ident: 'bob', localPort: 40001 }),
    ]);
    const lines = out
      .trimEnd()
      .split('\n')
      .filter((l) => !l.startsWith('#'));
    expect(lines).toHaveLength(2);
    expect(out).toContain('lport 40000 { reply "alice" }');
    expect(out).toContain('lport 40001 { reply "bob" }');
  });

  it('skips entries missing an address, port, or ident', () => {
    const out = formatOidentdConfig([
      entry({ ident: '' }),
      entry({ remoteAddress: '' }),
      entry({ localPort: 0 }),
    ]);
    expect(
      out
        .trimEnd()
        .split('\n')
        .filter((l) => !l.startsWith('#')),
    ).toHaveLength(0);
  });

  it('escapes backslashes and quotes so a reply cannot inject a second directive', () => {
    const out = formatOidentdConfig([entry({ ident: 'a"b\\c' })]);
    expect(out).toContain('{ reply "a\\"b\\\\c" }');
  });
});

describe('oidentd file writer', () => {
  let dir: string;
  let file: string;
  const registered: number[] = [];

  beforeEach(() => {
    vi.spyOn(console, 'log').mockImplementation(() => {});
    vi.spyOn(console, 'error').mockImplementation(() => {});
    dir = fs.mkdtempSync(path.join(os.tmpdir(), 'lurker-oidentd-'));
    file = path.join(dir, '.oidentd.conf');
    process.env.LURKER_OIDENTD_FILE = file;
  });

  afterEach(async () => {
    // Drain the map so leftover entries can't bleed into the next test's file.
    for (const id of registered.splice(0)) unregisterIdent(id);
    await flush();
    delete process.env.LURKER_OIDENTD_FILE;
    fs.rmSync(dir, { recursive: true, force: true });
    vi.restoreAllMocks();
  });

  it('resolves the path and reports enabled from the env var', () => {
    expect(isOidentdFileEnabled()).toBe(true);
    expect(oidentdFilePath()).toBe(file);
  });

  it('expands a leading ~ in the path', () => {
    process.env.LURKER_OIDENTD_FILE = '~/.oidentd.conf';
    expect(oidentdFilePath()).toBe(path.join(os.homedir(), '.oidentd.conf'));
  });

  it('writes a registered ident to the file, then removes it on unregister', async () => {
    const id = registerIdent(entry({ ident: 'carol' }));
    registered.push(id);
    await flush();
    expect(fs.readFileSync(file, 'utf8')).toContain('reply "carol"');

    unregisterIdent(registered.pop()!);
    await flush();
    expect(fs.readFileSync(file, 'utf8')).not.toContain('carol');
  });

  it('coalesces a synchronous burst of registrations into a single write', async () => {
    const writeSpy = vi.spyOn(fs.promises, 'writeFile');
    for (let i = 0; i < 5; i++) registered.push(registerIdent(entry({ localPort: 40000 + i })));
    await flush();
    expect(writeSpy).toHaveBeenCalledTimes(1);
    // All five still made it into that one write.
    expect(fs.readFileSync(file, 'utf8').match(/reply/g)).toHaveLength(5);
  });

  it('writes atomically via a temp file + rename', async () => {
    const renameSpy = vi.spyOn(fs.promises, 'rename');
    registered.push(registerIdent(entry()));
    await flush();
    expect(renameSpy).toHaveBeenCalledWith(`${file}.tmp`, file);
    expect(fs.existsSync(`${file}.tmp`)).toBe(false);
  });

  it('does not schedule a write when the mode is disabled', async () => {
    delete process.env.LURKER_OIDENTD_FILE;
    const writeSpy = vi.spyOn(fs.promises, 'writeFile');
    registered.push(registerIdent(entry()));
    await flush();
    expect(writeSpy).not.toHaveBeenCalled();
    process.env.LURKER_OIDENTD_FILE = file; // restore for afterEach drain
  });

  it('initOidentdFile writes a fresh header-only file on boot', () => {
    fs.writeFileSync(file, 'stale from a previous run\n');
    initOidentdFile();
    expect(fs.readFileSync(file, 'utf8')).toBe(
      '# Generated by Lurker — do not edit; overwritten on every IRC (dis)connect.\n',
    );
  });

  it('stopOidentdFile truncates lingering mappings to the header', async () => {
    registered.push(registerIdent(entry({ ident: 'dave' })));
    await flush();
    expect(fs.readFileSync(file, 'utf8')).toContain('dave');
    stopOidentdFile();
    expect(fs.readFileSync(file, 'utf8')).not.toContain('dave');
  });
});
